### ISSUE TITLE
ImportError: cannot import name indent

### ISSUE THREAD

**Issue by iammatthias** [GjjvdBurg/HugoPhotoSwipe#1]
Python 2.7.13
pip 9.0.1

I keep getting this error when I run `hps init`: 

```Traceback (most recent call last):
  File "/usr/local/bin/hps", line 11, in <module>
    from hugophotoswipe.ui import main
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/ui.py", line 14, in <module>
    from .hugophotoswipe import HugoPhotoSwipe
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/hugophotoswipe.py", line 14, in <module>
    from .album import Album
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/album.py", line 19, in <module>
    from .photo import Photo
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/photo.py", line 18, in <module>
    from textwrap import wrap, indent
ImportError: cannot import name indent 
```

If I remove `indent` from `from textwrap import wrap, indent` I get this error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/hps", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/ui.py", line 19, in main
    hps = HugoPhotoSwipe()
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/hugophotoswipe.py", line 24, in __init__
    self._albums = self._load_albums()
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/hugophotoswipe.py", line 92, in _load_albums
    local_objects = os.listdir()
TypeError: listdir() takes exactly 1 argument (0 given)
```

**Comment by GjjvdBurg** [comment]
Thanks for checking out the code and letting me know about this!  Currently
only Python 3 is supported, so you may want to try it with that.

Please let me know if you encounter any other problems.

**Comment by GjjvdBurg** [comment]
@iammatthias it should work in Python 2 now as well. Let me know if you encounter any other problems.
