### ISSUE TITLE
Error while running hps update

### ISSUE THREAD

**Issue by onedrawingperday** [GjjvdBurg/HugoPhotoSwipe#15]
Hello I just upgraded to HugoPhotoswipe 0.0.15 and when I ran `hps update` I got the following
```
Traceback (most recent call last):
  File "/usr/local/bin/hps", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/ui.py", line 36, in main
    hps.update(name=album)
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/hugophotoswipe.py", line 56, in update
    album.update()
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/album.py", line 276, in update
    photo.create_sizes()
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/photo.py", line 120, in create_sizes
    self.create_rescaled('large')
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/photo.py", line 138, in create_rescaled
    nimg = self.original_image.resize((nwidth, nheight), Image.ANTIALIAS)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1645, in resize
    return self._new(self.im.resize(size, resample))
TypeError: integer argument expected, got float
```
The contents of hugophotoswipe.yml are the following:

```
album_file: album.yml
cover_filename: coverimage.jpg
dim_max_cover: 600x600
dim_max_large: 1280
dim_max_small: 1024
dim_max_thumb: 256x256
dirname_large: large
dirname_small: small
dirname_thumb: thumb
jpeg_optimize: True
jpeg_progressive: False
jpeg_quality: 75
markdown_dir: /home/alex/hps/md
output_dir: /home/alex/hps/out
output_format: jpg
photo_dir: images
smartcrop_js_path:
url_prefix:
use_smartcrop_js: False
```
Any pointers?

**EDIT**
As HugoPhotoSwipe is crucial for my work flow I have downgraded to version 0.0.14 for now.

I've looked around the web for this error. And it seems that something is wrong with the way the images are resized.

**Comment by GjjvdBurg** [comment]
My bad, apparently ``round`` returns a ``float`` in python 2 but an ``int`` in Python 3. I'll be more careful testing in the future. You should be able to upload to version 0.0.16 to get rid of this error.

**Comment by onedrawingperday** [comment]
@GjjvdBurg Thank you for the hotfix! Upgraded to 0.0.16 and everything is working fine -including the new features-.
