### ISSUE TITLE
Error on First Run (Ubuntu 16.04/Python 2.7.12)

### ISSUE THREAD

**Issue by jbrice** [GjjvdBurg/HugoPhotoSwipe#19]
After a trouble-free install follwing the recommended procedure, running `hps` with any argument (or none) results in:
```Traceback (most recent call last):
  File "/usr/local/bin/hps", line 11, in <module>
    from hugophotoswipe.ui import main
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/ui.py", line 19, in <module>
    from .hugophotoswipe import HugoPhotoSwipe
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/hugophotoswipe.py", line 19, in <module>
    from .album import Album
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/album.py", line 22, in <module>
    from .conf import settings
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/conf.py", line 132, in <module>
    settings = load_settings()
  File "/usr/local/lib/python2.7/dist-packages/hugophotoswipe/conf.py", line 129, in load_settings
    return Settings(**data)
TypeError: type object argument after ** must be a mapping, not NoneType```

Suggestions please as to why this is falling apart even before doing an "init" as Python is not my thing.  This is Python 2.7.12.

**Comment by GjjvdBurg** [comment]
I have no idea why this is happening and this error is quite old now. If this is still a problem please reopen the issue and I'll take another look.
