### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by iammatthias** [GjjvdBurg/HugoPhotoSwipe#2]
Thanks for the help with #1, and thank you for building this script! 

I am now able to run `hps init` and `hps new`. I have configured my YAML file to point to my Hugo site directory: 
```
---
album_file: album.yml
cover_filename: coverimage.jpg
dim_coverimage: 600
dim_max_large: 1600
dim_max_small: 800
dim_thumbnail: 256
dirname_large: large
dirname_small: small
dirname_thumb: thumb
markdown_dir: /Users/iammatthias/Sites/Hugo/com/content/gal
output_dir: /Users/iammatthias/Sites/Hugo/com/src/images
output_format: jpg
photo_dir: photos
smartcrop_js_path:
url_prefix:
use_smartcrop_js: False
```

and now I'm getting this issue when I run `hps update`: 

```
Traceback (most recent call last):
  File "/usr/local/bin/hps", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/ui.py", line 23, in main
    hps.update(name=album)
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/hugophotoswipe.py", line 58, in update
    album.update()
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/album.py", line 252, in update
    self.create_markdown()
  File "/usr/local/lib/python2.7/site-packages/hugophotoswipe/album.py", line 115, in create_markdown
    proptxt = ["%s = \"%s\"" % (k, v) for k, v in self.properties.items()]
AttributeError: 'NoneType' object has no attribute 'items'
```

I get the same error when I try to run the scrip with Python 3: 

```
Traceback (most recent call last):
  File "/usr/local/bin/hps", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hugophotoswipe/ui.py", line 23, in main
    hps.update(name=album)
  File "/usr/local/lib/python3.6/site-packages/hugophotoswipe/hugophotoswipe.py", line 58, in update
    album.update()
  File "/usr/local/lib/python3.6/site-packages/hugophotoswipe/album.py", line 252, in update
    self.create_markdown()
  File "/usr/local/lib/python3.6/site-packages/hugophotoswipe/album.py", line 115, in create_markdown
    proptxt = ["%s = \"%s\"" % (k, v) for k, v in self.properties.items()]
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by GjjvdBurg** [comment]
Ah, this is a little oversight on my part. You need a ``properties:`` line
in the YAML of the album. I'll fix this bug as soon as possible to but for
now adding that should fix it.

**Comment by GjjvdBurg** [comment]
@iammatthias I've updated the code, should be fixed now. Thanks for your thorough testing, and let me know if you run into any other problems.
